/*
 * GitHubAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.github.api.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.BaseModel;

/**
 * This is a model class for Base type.
 */
public class Base {
    private String ref;
    private String sha;
    private Repo repo;

    /**
     * Default constructor.
     */
    public Base() {
    }

    /**
     * Initialization constructor.
     * @param  ref  String value for ref.
     * @param  sha  String value for sha.
     * @param  repo  Repo value for repo.
     */
    public Base(
            String ref,
            String sha,
            Repo repo) {
        this.ref = ref;
        this.sha = sha;
        this.repo = repo;
    }

    /**
     * Getter for Ref.
     * @return Returns the String
     */
    @JsonGetter("ref")
    public String getRef() {
        return ref;
    }

    /**
     * Setter for Ref.
     * @param ref Value for String
     */
    @JsonSetter("ref")
    public void setRef(String ref) {
        this.ref = ref;
    }

    /**
     * Getter for Sha.
     * @return Returns the String
     */
    @JsonGetter("sha")
    public String getSha() {
        return sha;
    }

    /**
     * Setter for Sha.
     * @param sha Value for String
     */
    @JsonSetter("sha")
    public void setSha(String sha) {
        this.sha = sha;
    }

    /**
     * Getter for Repo.
     * @return Returns the Repo
     */
    @JsonGetter("repo")
    public Repo getRepo() {
        return repo;
    }

    /**
     * Setter for Repo.
     * @param repo Value for Repo
     */
    @JsonSetter("repo")
    public void setRepo(Repo repo) {
        this.repo = repo;
    }

    /**
     * Converts this Base into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "Base [" + "ref=" + ref + ", sha=" + sha + ", repo=" + repo + "]";
    }

    /**
     * Builds a new {@link Base.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link Base.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(ref, sha, repo);
        return builder;
    }

    /**
     * Class to build instances of {@link Base}.
     */
    public static class Builder {
        private String ref;
        private String sha;
        private Repo repo;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  ref  String value for ref.
         * @param  sha  String value for sha.
         * @param  repo  Repo value for repo.
         */
        public Builder(String ref, String sha, Repo repo) {
            this.ref = ref;
            this.sha = sha;
            this.repo = repo;
        }

        /**
         * Setter for ref.
         * @param  ref  String value for ref.
         * @return Builder
         */
        public Builder ref(String ref) {
            this.ref = ref;
            return this;
        }

        /**
         * Setter for sha.
         * @param  sha  String value for sha.
         * @return Builder
         */
        public Builder sha(String sha) {
            this.sha = sha;
            return this;
        }

        /**
         * Setter for repo.
         * @param  repo  Repo value for repo.
         * @return Builder
         */
        public Builder repo(Repo repo) {
            this.repo = repo;
            return this;
        }

        /**
         * Builds a new {@link Base} object using the set fields.
         * @return {@link Base}
         */
        public Base build() {
            return new Base(ref, sha, repo);
        }
    }
}
