/*
 * GitHubAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.github.api.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.github.api.DateTimeHelper;
import io.apimatic.core.types.BaseModel;
import java.time.LocalDateTime;

/**
 * This is a model class for Committer18 type.
 */
public class Committer18 {
    private LocalDateTime date;
    private String email;
    private String name;
    private String username;

    /**
     * Default constructor.
     */
    public Committer18() {
    }

    /**
     * Initialization constructor.
     * @param  date  LocalDateTime value for date.
     * @param  email  String value for email.
     * @param  name  String value for name.
     * @param  username  String value for username.
     */
    public Committer18(
            LocalDateTime date,
            String email,
            String name,
            String username) {
        this.date = date;
        this.email = email;
        this.name = name;
        this.username = username;
    }

    /**
     * Getter for Date.
     * @return Returns the LocalDateTime
     */
    @JsonGetter("date")
    @JsonSerialize(using = DateTimeHelper.Rfc8601DateTimeSerializer.class)
    public LocalDateTime getDate() {
        return date;
    }

    /**
     * Setter for Date.
     * @param date Value for LocalDateTime
     */
    @JsonSetter("date")
    @JsonDeserialize(using = DateTimeHelper.Rfc8601DateTimeDeserializer.class)
    public void setDate(LocalDateTime date) {
        this.date = date;
    }

    /**
     * Getter for Email.
     * @return Returns the String
     */
    @JsonGetter("email")
    public String getEmail() {
        return email;
    }

    /**
     * Setter for Email.
     * @param email Value for String
     */
    @JsonSetter("email")
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * Getter for Name.
     * The git author's name.
     * @return Returns the String
     */
    @JsonGetter("name")
    public String getName() {
        return name;
    }

    /**
     * Setter for Name.
     * The git author's name.
     * @param name Value for String
     */
    @JsonSetter("name")
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Getter for Username.
     * @return Returns the String
     */
    @JsonGetter("username")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getUsername() {
        return username;
    }

    /**
     * Setter for Username.
     * @param username Value for String
     */
    @JsonSetter("username")
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * Converts this Committer18 into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "Committer18 [" + "date=" + date + ", email=" + email + ", name=" + name
                + ", username=" + username + "]";
    }

    /**
     * Builds a new {@link Committer18.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link Committer18.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(date, email, name)
                .username(getUsername());
        return builder;
    }

    /**
     * Class to build instances of {@link Committer18}.
     */
    public static class Builder {
        private LocalDateTime date;
        private String email;
        private String name;
        private String username;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  date  LocalDateTime value for date.
         * @param  email  String value for email.
         * @param  name  String value for name.
         */
        public Builder(LocalDateTime date, String email, String name) {
            this.date = date;
            this.email = email;
            this.name = name;
        }

        /**
         * Setter for date.
         * @param  date  LocalDateTime value for date.
         * @return Builder
         */
        public Builder date(LocalDateTime date) {
            this.date = date;
            return this;
        }

        /**
         * Setter for email.
         * @param  email  String value for email.
         * @return Builder
         */
        public Builder email(String email) {
            this.email = email;
            return this;
        }

        /**
         * Setter for name.
         * @param  name  String value for name.
         * @return Builder
         */
        public Builder name(String name) {
            this.name = name;
            return this;
        }

        /**
         * Setter for username.
         * @param  username  String value for username.
         * @return Builder
         */
        public Builder username(String username) {
            this.username = username;
            return this;
        }

        /**
         * Builds a new {@link Committer18} object using the set fields.
         * @return {@link Committer18}
         */
        public Committer18 build() {
            return new Committer18(date, email, name, username);
        }
    }
}
