/*
 * GitHubAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.github.api.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.BaseModel;

/**
 * This is a model class for Login1 type.
 */
public class Login1 {
    private String from;

    /**
     * Default constructor.
     */
    public Login1() {
    }

    /**
     * Initialization constructor.
     * @param  from  String value for from.
     */
    public Login1(
            String from) {
        this.from = from;
    }

    /**
     * Getter for From.
     * @return Returns the String
     */
    @JsonGetter("from")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getFrom() {
        return from;
    }

    /**
     * Setter for From.
     * @param from Value for String
     */
    @JsonSetter("from")
    public void setFrom(String from) {
        this.from = from;
    }

    /**
     * Converts this Login1 into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "Login1 [" + "from=" + from + "]";
    }

    /**
     * Builds a new {@link Login1.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link Login1.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .from(getFrom());
        return builder;
    }

    /**
     * Class to build instances of {@link Login1}.
     */
    public static class Builder {
        private String from;



        /**
         * Setter for from.
         * @param  from  String value for from.
         * @return Builder
         */
        public Builder from(String from) {
            this.from = from;
            return this;
        }

        /**
         * Builds a new {@link Login1} object using the set fields.
         * @return {@link Login1}
         */
        public Login1 build() {
            return new Login1(from);
        }
    }
}
