/*
 * GitHubAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.github.api.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.BaseModel;

/**
 * This is a model class for NotificationsResponse type.
 */
public class NotificationsResponse {
    private String message;

    /**
     * Default constructor.
     */
    public NotificationsResponse() {
    }

    /**
     * Initialization constructor.
     * @param  message  String value for message.
     */
    public NotificationsResponse(
            String message) {
        this.message = message;
    }

    /**
     * Getter for Message.
     * @return Returns the String
     */
    @JsonGetter("message")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getMessage() {
        return message;
    }

    /**
     * Setter for Message.
     * @param message Value for String
     */
    @JsonSetter("message")
    public void setMessage(String message) {
        this.message = message;
    }

    /**
     * Converts this NotificationsResponse into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "NotificationsResponse [" + "message=" + message + "]";
    }

    /**
     * Builds a new {@link NotificationsResponse.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link NotificationsResponse.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .message(getMessage());
        return builder;
    }

    /**
     * Class to build instances of {@link NotificationsResponse}.
     */
    public static class Builder {
        private String message;



        /**
         * Setter for message.
         * @param  message  String value for message.
         * @return Builder
         */
        public Builder message(String message) {
            this.message = message;
            return this;
        }

        /**
         * Builds a new {@link NotificationsResponse} object using the set fields.
         * @return {@link NotificationsResponse}
         */
        public NotificationsResponse build() {
            return new NotificationsResponse(message);
        }
    }
}
