/*
 * GitHubAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.github.api.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import io.apimatic.core.types.BaseModel;
import io.apimatic.core.types.OptionalNullable;

/**
 * This is a model class for PackageFile3 type.
 */
public class PackageFile3 {
    private String contentType;
    private String createdAt;
    private String downloadUrl;
    private Integer id;
    private OptionalNullable<String> md5;
    private String name;
    private OptionalNullable<String> sha1;
    private String sha256;
    private Integer size;
    private String state;
    private String updatedAt;

    /**
     * Default constructor.
     */
    public PackageFile3() {
    }

    /**
     * Initialization constructor.
     * @param  contentType  String value for contentType.
     * @param  createdAt  String value for createdAt.
     * @param  downloadUrl  String value for downloadUrl.
     * @param  id  Integer value for id.
     * @param  md5  String value for md5.
     * @param  name  String value for name.
     * @param  sha1  String value for sha1.
     * @param  sha256  String value for sha256.
     * @param  size  Integer value for size.
     * @param  state  String value for state.
     * @param  updatedAt  String value for updatedAt.
     */
    public PackageFile3(
            String contentType,
            String createdAt,
            String downloadUrl,
            Integer id,
            String md5,
            String name,
            String sha1,
            String sha256,
            Integer size,
            String state,
            String updatedAt) {
        this.contentType = contentType;
        this.createdAt = createdAt;
        this.downloadUrl = downloadUrl;
        this.id = id;
        this.md5 = OptionalNullable.of(md5);
        this.name = name;
        this.sha1 = OptionalNullable.of(sha1);
        this.sha256 = sha256;
        this.size = size;
        this.state = state;
        this.updatedAt = updatedAt;
    }

    /**
     * Internal initialization constructor.
     */
    protected PackageFile3(String contentType, String createdAt, String downloadUrl, Integer id,
            OptionalNullable<String> md5, String name, OptionalNullable<String> sha1, String sha256,
            Integer size, String state, String updatedAt) {
        this.contentType = contentType;
        this.createdAt = createdAt;
        this.downloadUrl = downloadUrl;
        this.id = id;
        this.md5 = md5;
        this.name = name;
        this.sha1 = sha1;
        this.sha256 = sha256;
        this.size = size;
        this.state = state;
        this.updatedAt = updatedAt;
    }

    /**
     * Getter for ContentType.
     * @return Returns the String
     */
    @JsonGetter("content_type")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getContentType() {
        return contentType;
    }

    /**
     * Setter for ContentType.
     * @param contentType Value for String
     */
    @JsonSetter("content_type")
    public void setContentType(String contentType) {
        this.contentType = contentType;
    }

    /**
     * Getter for CreatedAt.
     * @return Returns the String
     */
    @JsonGetter("created_at")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getCreatedAt() {
        return createdAt;
    }

    /**
     * Setter for CreatedAt.
     * @param createdAt Value for String
     */
    @JsonSetter("created_at")
    public void setCreatedAt(String createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * Getter for DownloadUrl.
     * @return Returns the String
     */
    @JsonGetter("download_url")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getDownloadUrl() {
        return downloadUrl;
    }

    /**
     * Setter for DownloadUrl.
     * @param downloadUrl Value for String
     */
    @JsonSetter("download_url")
    public void setDownloadUrl(String downloadUrl) {
        this.downloadUrl = downloadUrl;
    }

    /**
     * Getter for Id.
     * @return Returns the Integer
     */
    @JsonGetter("id")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Integer getId() {
        return id;
    }

    /**
     * Setter for Id.
     * @param id Value for Integer
     */
    @JsonSetter("id")
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * Internal Getter for Md5.
     * @return Returns the Internal String
     */
    @JsonGetter("md5")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonSerialize(using = OptionalNullable.Serializer.class)
    protected OptionalNullable<String> internalGetMd5() {
        return this.md5;
    }

    /**
     * Getter for Md5.
     * @return Returns the String
     */
    public String getMd5() {
        return OptionalNullable.getFrom(md5);
    }

    /**
     * Setter for Md5.
     * @param md5 Value for String
     */
    @JsonSetter("md5")
    public void setMd5(String md5) {
        this.md5 = OptionalNullable.of(md5);
    }

    /**
     * UnSetter for Md5.
     */
    public void unsetMd5() {
        md5 = null;
    }

    /**
     * Getter for Name.
     * @return Returns the String
     */
    @JsonGetter("name")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getName() {
        return name;
    }

    /**
     * Setter for Name.
     * @param name Value for String
     */
    @JsonSetter("name")
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Internal Getter for Sha1.
     * @return Returns the Internal String
     */
    @JsonGetter("sha1")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonSerialize(using = OptionalNullable.Serializer.class)
    protected OptionalNullable<String> internalGetSha1() {
        return this.sha1;
    }

    /**
     * Getter for Sha1.
     * @return Returns the String
     */
    public String getSha1() {
        return OptionalNullable.getFrom(sha1);
    }

    /**
     * Setter for Sha1.
     * @param sha1 Value for String
     */
    @JsonSetter("sha1")
    public void setSha1(String sha1) {
        this.sha1 = OptionalNullable.of(sha1);
    }

    /**
     * UnSetter for Sha1.
     */
    public void unsetSha1() {
        sha1 = null;
    }

    /**
     * Getter for Sha256.
     * @return Returns the String
     */
    @JsonGetter("sha256")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getSha256() {
        return sha256;
    }

    /**
     * Setter for Sha256.
     * @param sha256 Value for String
     */
    @JsonSetter("sha256")
    public void setSha256(String sha256) {
        this.sha256 = sha256;
    }

    /**
     * Getter for Size.
     * @return Returns the Integer
     */
    @JsonGetter("size")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Integer getSize() {
        return size;
    }

    /**
     * Setter for Size.
     * @param size Value for Integer
     */
    @JsonSetter("size")
    public void setSize(Integer size) {
        this.size = size;
    }

    /**
     * Getter for State.
     * @return Returns the String
     */
    @JsonGetter("state")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getState() {
        return state;
    }

    /**
     * Setter for State.
     * @param state Value for String
     */
    @JsonSetter("state")
    public void setState(String state) {
        this.state = state;
    }

    /**
     * Getter for UpdatedAt.
     * @return Returns the String
     */
    @JsonGetter("updated_at")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getUpdatedAt() {
        return updatedAt;
    }

    /**
     * Setter for UpdatedAt.
     * @param updatedAt Value for String
     */
    @JsonSetter("updated_at")
    public void setUpdatedAt(String updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * Converts this PackageFile3 into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "PackageFile3 [" + "contentType=" + contentType + ", createdAt=" + createdAt
                + ", downloadUrl=" + downloadUrl + ", id=" + id + ", md5=" + md5 + ", name=" + name
                + ", sha1=" + sha1 + ", sha256=" + sha256 + ", size=" + size + ", state=" + state
                + ", updatedAt=" + updatedAt + "]";
    }

    /**
     * Builds a new {@link PackageFile3.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link PackageFile3.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .contentType(getContentType())
                .createdAt(getCreatedAt())
                .downloadUrl(getDownloadUrl())
                .id(getId())
                .name(getName())
                .sha256(getSha256())
                .size(getSize())
                .state(getState())
                .updatedAt(getUpdatedAt());
        builder.md5 = internalGetMd5();
        builder.sha1 = internalGetSha1();
        return builder;
    }

    /**
     * Class to build instances of {@link PackageFile3}.
     */
    public static class Builder {
        private String contentType;
        private String createdAt;
        private String downloadUrl;
        private Integer id;
        private OptionalNullable<String> md5;
        private String name;
        private OptionalNullable<String> sha1;
        private String sha256;
        private Integer size;
        private String state;
        private String updatedAt;



        /**
         * Setter for contentType.
         * @param  contentType  String value for contentType.
         * @return Builder
         */
        public Builder contentType(String contentType) {
            this.contentType = contentType;
            return this;
        }

        /**
         * Setter for createdAt.
         * @param  createdAt  String value for createdAt.
         * @return Builder
         */
        public Builder createdAt(String createdAt) {
            this.createdAt = createdAt;
            return this;
        }

        /**
         * Setter for downloadUrl.
         * @param  downloadUrl  String value for downloadUrl.
         * @return Builder
         */
        public Builder downloadUrl(String downloadUrl) {
            this.downloadUrl = downloadUrl;
            return this;
        }

        /**
         * Setter for id.
         * @param  id  Integer value for id.
         * @return Builder
         */
        public Builder id(Integer id) {
            this.id = id;
            return this;
        }

        /**
         * Setter for md5.
         * @param  md5  String value for md5.
         * @return Builder
         */
        public Builder md5(String md5) {
            this.md5 = OptionalNullable.of(md5);
            return this;
        }

        /**
         * UnSetter for md5.
         * @return Builder
         */
        public Builder unsetMd5() {
            md5 = null;
            return this;
        }

        /**
         * Setter for name.
         * @param  name  String value for name.
         * @return Builder
         */
        public Builder name(String name) {
            this.name = name;
            return this;
        }

        /**
         * Setter for sha1.
         * @param  sha1  String value for sha1.
         * @return Builder
         */
        public Builder sha1(String sha1) {
            this.sha1 = OptionalNullable.of(sha1);
            return this;
        }

        /**
         * UnSetter for sha1.
         * @return Builder
         */
        public Builder unsetSha1() {
            sha1 = null;
            return this;
        }

        /**
         * Setter for sha256.
         * @param  sha256  String value for sha256.
         * @return Builder
         */
        public Builder sha256(String sha256) {
            this.sha256 = sha256;
            return this;
        }

        /**
         * Setter for size.
         * @param  size  Integer value for size.
         * @return Builder
         */
        public Builder size(Integer size) {
            this.size = size;
            return this;
        }

        /**
         * Setter for state.
         * @param  state  String value for state.
         * @return Builder
         */
        public Builder state(String state) {
            this.state = state;
            return this;
        }

        /**
         * Setter for updatedAt.
         * @param  updatedAt  String value for updatedAt.
         * @return Builder
         */
        public Builder updatedAt(String updatedAt) {
            this.updatedAt = updatedAt;
            return this;
        }

        /**
         * Builds a new {@link PackageFile3} object using the set fields.
         * @return {@link PackageFile3}
         */
        public PackageFile3 build() {
            return new PackageFile3(contentType, createdAt, downloadUrl, id, md5, name, sha1,
                    sha256, size, state, updatedAt);
        }
    }
}
