/*
 * GitHubAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.github.api.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.BaseModel;
import java.util.List;

/**
 * This is a model class for Preferences type.
 */
public class Preferences {
    private List<AutoTriggerCheck> autoTriggerChecks;

    /**
     * Default constructor.
     */
    public Preferences() {
    }

    /**
     * Initialization constructor.
     * @param  autoTriggerChecks  List of AutoTriggerCheck value for autoTriggerChecks.
     */
    public Preferences(
            List<AutoTriggerCheck> autoTriggerChecks) {
        this.autoTriggerChecks = autoTriggerChecks;
    }

    /**
     * Getter for AutoTriggerChecks.
     * @return Returns the List of AutoTriggerCheck
     */
    @JsonGetter("auto_trigger_checks")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public List<AutoTriggerCheck> getAutoTriggerChecks() {
        return autoTriggerChecks;
    }

    /**
     * Setter for AutoTriggerChecks.
     * @param autoTriggerChecks Value for List of AutoTriggerCheck
     */
    @JsonSetter("auto_trigger_checks")
    public void setAutoTriggerChecks(List<AutoTriggerCheck> autoTriggerChecks) {
        this.autoTriggerChecks = autoTriggerChecks;
    }

    /**
     * Converts this Preferences into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "Preferences [" + "autoTriggerChecks=" + autoTriggerChecks + "]";
    }

    /**
     * Builds a new {@link Preferences.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link Preferences.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .autoTriggerChecks(getAutoTriggerChecks());
        return builder;
    }

    /**
     * Class to build instances of {@link Preferences}.
     */
    public static class Builder {
        private List<AutoTriggerCheck> autoTriggerChecks;



        /**
         * Setter for autoTriggerChecks.
         * @param  autoTriggerChecks  List of AutoTriggerCheck value for autoTriggerChecks.
         * @return Builder
         */
        public Builder autoTriggerChecks(List<AutoTriggerCheck> autoTriggerChecks) {
            this.autoTriggerChecks = autoTriggerChecks;
            return this;
        }

        /**
         * Builds a new {@link Preferences} object using the set fields.
         * @return {@link Preferences}
         */
        public Preferences build() {
            return new Preferences(autoTriggerChecks);
        }
    }
}
