/*
 * GitHubAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.github.api.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.BaseModel;
import java.util.List;

/**
 * This is a model class for ReposActionsVariablesResponse type.
 */
public class ReposActionsVariablesResponse {
    private int totalCount;
    private List<ActionsVariable> variables;

    /**
     * Default constructor.
     */
    public ReposActionsVariablesResponse() {
    }

    /**
     * Initialization constructor.
     * @param  totalCount  int value for totalCount.
     * @param  variables  List of ActionsVariable value for variables.
     */
    public ReposActionsVariablesResponse(
            int totalCount,
            List<ActionsVariable> variables) {
        this.totalCount = totalCount;
        this.variables = variables;
    }

    /**
     * Getter for TotalCount.
     * @return Returns the int
     */
    @JsonGetter("total_count")
    public int getTotalCount() {
        return totalCount;
    }

    /**
     * Setter for TotalCount.
     * @param totalCount Value for int
     */
    @JsonSetter("total_count")
    public void setTotalCount(int totalCount) {
        this.totalCount = totalCount;
    }

    /**
     * Getter for Variables.
     * @return Returns the List of ActionsVariable
     */
    @JsonGetter("variables")
    public List<ActionsVariable> getVariables() {
        return variables;
    }

    /**
     * Setter for Variables.
     * @param variables Value for List of ActionsVariable
     */
    @JsonSetter("variables")
    public void setVariables(List<ActionsVariable> variables) {
        this.variables = variables;
    }

    /**
     * Converts this ReposActionsVariablesResponse into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "ReposActionsVariablesResponse [" + "totalCount=" + totalCount + ", variables="
                + variables + "]";
    }

    /**
     * Builds a new {@link ReposActionsVariablesResponse.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link ReposActionsVariablesResponse.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(totalCount, variables);
        return builder;
    }

    /**
     * Class to build instances of {@link ReposActionsVariablesResponse}.
     */
    public static class Builder {
        private int totalCount;
        private List<ActionsVariable> variables;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  totalCount  int value for totalCount.
         * @param  variables  List of ActionsVariable value for variables.
         */
        public Builder(int totalCount, List<ActionsVariable> variables) {
            this.totalCount = totalCount;
            this.variables = variables;
        }

        /**
         * Setter for totalCount.
         * @param  totalCount  int value for totalCount.
         * @return Builder
         */
        public Builder totalCount(int totalCount) {
            this.totalCount = totalCount;
            return this;
        }

        /**
         * Setter for variables.
         * @param  variables  List of ActionsVariable value for variables.
         * @return Builder
         */
        public Builder variables(List<ActionsVariable> variables) {
            this.variables = variables;
            return this;
        }

        /**
         * Builds a new {@link ReposActionsVariablesResponse} object using the set fields.
         * @return {@link ReposActionsVariablesResponse}
         */
        public ReposActionsVariablesResponse build() {
            return new ReposActionsVariablesResponse(totalCount, variables);
        }
    }
}
