/*
 * GitHubAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.github.api.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.github.api.DateTimeHelper;
import io.apimatic.core.types.BaseModel;
import java.time.LocalDateTime;

/**
 * This is a model class for SimpleCommit type.
 */
public class SimpleCommit {
    private String id;
    private String treeId;
    private String message;
    private LocalDateTime timestamp;
    private Object author;
    private Object committer;

    /**
     * Default constructor.
     */
    public SimpleCommit() {
    }

    /**
     * Initialization constructor.
     * @param  id  String value for id.
     * @param  treeId  String value for treeId.
     * @param  message  String value for message.
     * @param  timestamp  LocalDateTime value for timestamp.
     * @param  author  Object value for author.
     * @param  committer  Object value for committer.
     */
    public SimpleCommit(
            String id,
            String treeId,
            String message,
            LocalDateTime timestamp,
            Object author,
            Object committer) {
        this.id = id;
        this.treeId = treeId;
        this.message = message;
        this.timestamp = timestamp;
        this.author = author;
        this.committer = committer;
    }

    /**
     * Getter for Id.
     * @return Returns the String
     */
    @JsonGetter("id")
    public String getId() {
        return id;
    }

    /**
     * Setter for Id.
     * @param id Value for String
     */
    @JsonSetter("id")
    public void setId(String id) {
        this.id = id;
    }

    /**
     * Getter for TreeId.
     * @return Returns the String
     */
    @JsonGetter("tree_id")
    public String getTreeId() {
        return treeId;
    }

    /**
     * Setter for TreeId.
     * @param treeId Value for String
     */
    @JsonSetter("tree_id")
    public void setTreeId(String treeId) {
        this.treeId = treeId;
    }

    /**
     * Getter for Message.
     * @return Returns the String
     */
    @JsonGetter("message")
    public String getMessage() {
        return message;
    }

    /**
     * Setter for Message.
     * @param message Value for String
     */
    @JsonSetter("message")
    public void setMessage(String message) {
        this.message = message;
    }

    /**
     * Getter for Timestamp.
     * @return Returns the LocalDateTime
     */
    @JsonGetter("timestamp")
    @JsonSerialize(using = DateTimeHelper.Rfc8601DateTimeSerializer.class)
    public LocalDateTime getTimestamp() {
        return timestamp;
    }

    /**
     * Setter for Timestamp.
     * @param timestamp Value for LocalDateTime
     */
    @JsonSetter("timestamp")
    @JsonDeserialize(using = DateTimeHelper.Rfc8601DateTimeDeserializer.class)
    public void setTimestamp(LocalDateTime timestamp) {
        this.timestamp = timestamp;
    }

    /**
     * Getter for Author.
     * @return Returns the Object
     */
    @JsonGetter("author")
    public Object getAuthor() {
        return author;
    }

    /**
     * Setter for Author.
     * @param author Value for Object
     */
    @JsonSetter("author")
    public void setAuthor(Object author) {
        this.author = author;
    }

    /**
     * Getter for Committer.
     * @return Returns the Object
     */
    @JsonGetter("committer")
    public Object getCommitter() {
        return committer;
    }

    /**
     * Setter for Committer.
     * @param committer Value for Object
     */
    @JsonSetter("committer")
    public void setCommitter(Object committer) {
        this.committer = committer;
    }

    /**
     * Converts this SimpleCommit into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "SimpleCommit [" + "id=" + id + ", treeId=" + treeId + ", message=" + message
                + ", timestamp=" + timestamp + ", author=" + author + ", committer=" + committer
                + "]";
    }

    /**
     * Builds a new {@link SimpleCommit.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link SimpleCommit.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(id, treeId, message, timestamp, author, committer);
        return builder;
    }

    /**
     * Class to build instances of {@link SimpleCommit}.
     */
    public static class Builder {
        private String id;
        private String treeId;
        private String message;
        private LocalDateTime timestamp;
        private Object author;
        private Object committer;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  id  String value for id.
         * @param  treeId  String value for treeId.
         * @param  message  String value for message.
         * @param  timestamp  LocalDateTime value for timestamp.
         * @param  author  Object value for author.
         * @param  committer  Object value for committer.
         */
        public Builder(String id, String treeId, String message, LocalDateTime timestamp,
                Object author, Object committer) {
            this.id = id;
            this.treeId = treeId;
            this.message = message;
            this.timestamp = timestamp;
            this.author = author;
            this.committer = committer;
        }

        /**
         * Setter for id.
         * @param  id  String value for id.
         * @return Builder
         */
        public Builder id(String id) {
            this.id = id;
            return this;
        }

        /**
         * Setter for treeId.
         * @param  treeId  String value for treeId.
         * @return Builder
         */
        public Builder treeId(String treeId) {
            this.treeId = treeId;
            return this;
        }

        /**
         * Setter for message.
         * @param  message  String value for message.
         * @return Builder
         */
        public Builder message(String message) {
            this.message = message;
            return this;
        }

        /**
         * Setter for timestamp.
         * @param  timestamp  LocalDateTime value for timestamp.
         * @return Builder
         */
        public Builder timestamp(LocalDateTime timestamp) {
            this.timestamp = timestamp;
            return this;
        }

        /**
         * Setter for author.
         * @param  author  Object value for author.
         * @return Builder
         */
        public Builder author(Object author) {
            this.author = author;
            return this;
        }

        /**
         * Setter for committer.
         * @param  committer  Object value for committer.
         * @return Builder
         */
        public Builder committer(Object committer) {
            this.committer = committer;
            return this;
        }

        /**
         * Builds a new {@link SimpleCommit} object using the set fields.
         * @return {@link SimpleCommit}
         */
        public SimpleCommit build() {
            return new SimpleCommit(id, treeId, message, timestamp, author, committer);
        }
    }
}
