/*
 * GitHubAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.github.api.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.BaseModel;

/**
 * This is a model class for Sponsorship type.
 */
public class Sponsorship {
    private String createdAt;
    private Author7 maintainer;
    private String nodeId;
    private String privacyLevel;
    private Object sponsor;
    private Object sponsorable;
    private Tier3 tier;

    /**
     * Default constructor.
     */
    public Sponsorship() {
    }

    /**
     * Initialization constructor.
     * @param  createdAt  String value for createdAt.
     * @param  nodeId  String value for nodeId.
     * @param  privacyLevel  String value for privacyLevel.
     * @param  sponsor  Object value for sponsor.
     * @param  sponsorable  Object value for sponsorable.
     * @param  tier  Tier3 value for tier.
     * @param  maintainer  Author7 value for maintainer.
     */
    public Sponsorship(
            String createdAt,
            String nodeId,
            String privacyLevel,
            Object sponsor,
            Object sponsorable,
            Tier3 tier,
            Author7 maintainer) {
        this.createdAt = createdAt;
        this.maintainer = maintainer;
        this.nodeId = nodeId;
        this.privacyLevel = privacyLevel;
        this.sponsor = sponsor;
        this.sponsorable = sponsorable;
        this.tier = tier;
    }

    /**
     * Getter for CreatedAt.
     * @return Returns the String
     */
    @JsonGetter("created_at")
    public String getCreatedAt() {
        return createdAt;
    }

    /**
     * Setter for CreatedAt.
     * @param createdAt Value for String
     */
    @JsonSetter("created_at")
    public void setCreatedAt(String createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * Getter for Maintainer.
     * @return Returns the Author7
     */
    @JsonGetter("maintainer")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Author7 getMaintainer() {
        return maintainer;
    }

    /**
     * Setter for Maintainer.
     * @param maintainer Value for Author7
     */
    @JsonSetter("maintainer")
    public void setMaintainer(Author7 maintainer) {
        this.maintainer = maintainer;
    }

    /**
     * Getter for NodeId.
     * @return Returns the String
     */
    @JsonGetter("node_id")
    public String getNodeId() {
        return nodeId;
    }

    /**
     * Setter for NodeId.
     * @param nodeId Value for String
     */
    @JsonSetter("node_id")
    public void setNodeId(String nodeId) {
        this.nodeId = nodeId;
    }

    /**
     * Getter for PrivacyLevel.
     * @return Returns the String
     */
    @JsonGetter("privacy_level")
    public String getPrivacyLevel() {
        return privacyLevel;
    }

    /**
     * Setter for PrivacyLevel.
     * @param privacyLevel Value for String
     */
    @JsonSetter("privacy_level")
    public void setPrivacyLevel(String privacyLevel) {
        this.privacyLevel = privacyLevel;
    }

    /**
     * Getter for Sponsor.
     * @return Returns the Object
     */
    @JsonGetter("sponsor")
    public Object getSponsor() {
        return sponsor;
    }

    /**
     * Setter for Sponsor.
     * @param sponsor Value for Object
     */
    @JsonSetter("sponsor")
    public void setSponsor(Object sponsor) {
        this.sponsor = sponsor;
    }

    /**
     * Getter for Sponsorable.
     * @return Returns the Object
     */
    @JsonGetter("sponsorable")
    public Object getSponsorable() {
        return sponsorable;
    }

    /**
     * Setter for Sponsorable.
     * @param sponsorable Value for Object
     */
    @JsonSetter("sponsorable")
    public void setSponsorable(Object sponsorable) {
        this.sponsorable = sponsorable;
    }

    /**
     * Getter for Tier.
     * @return Returns the Tier3
     */
    @JsonGetter("tier")
    public Tier3 getTier() {
        return tier;
    }

    /**
     * Setter for Tier.
     * @param tier Value for Tier3
     */
    @JsonSetter("tier")
    public void setTier(Tier3 tier) {
        this.tier = tier;
    }

    /**
     * Converts this Sponsorship into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "Sponsorship [" + "createdAt=" + createdAt + ", nodeId=" + nodeId + ", privacyLevel="
                + privacyLevel + ", sponsor=" + sponsor + ", sponsorable=" + sponsorable + ", tier="
                + tier + ", maintainer=" + maintainer + "]";
    }

    /**
     * Builds a new {@link Sponsorship.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link Sponsorship.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(createdAt, nodeId, privacyLevel, sponsor, sponsorable, tier)
                .maintainer(getMaintainer());
        return builder;
    }

    /**
     * Class to build instances of {@link Sponsorship}.
     */
    public static class Builder {
        private String createdAt;
        private String nodeId;
        private String privacyLevel;
        private Object sponsor;
        private Object sponsorable;
        private Tier3 tier;
        private Author7 maintainer;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  createdAt  String value for createdAt.
         * @param  nodeId  String value for nodeId.
         * @param  privacyLevel  String value for privacyLevel.
         * @param  sponsor  Object value for sponsor.
         * @param  sponsorable  Object value for sponsorable.
         * @param  tier  Tier3 value for tier.
         */
        public Builder(String createdAt, String nodeId, String privacyLevel, Object sponsor,
                Object sponsorable, Tier3 tier) {
            this.createdAt = createdAt;
            this.nodeId = nodeId;
            this.privacyLevel = privacyLevel;
            this.sponsor = sponsor;
            this.sponsorable = sponsorable;
            this.tier = tier;
        }

        /**
         * Setter for createdAt.
         * @param  createdAt  String value for createdAt.
         * @return Builder
         */
        public Builder createdAt(String createdAt) {
            this.createdAt = createdAt;
            return this;
        }

        /**
         * Setter for nodeId.
         * @param  nodeId  String value for nodeId.
         * @return Builder
         */
        public Builder nodeId(String nodeId) {
            this.nodeId = nodeId;
            return this;
        }

        /**
         * Setter for privacyLevel.
         * @param  privacyLevel  String value for privacyLevel.
         * @return Builder
         */
        public Builder privacyLevel(String privacyLevel) {
            this.privacyLevel = privacyLevel;
            return this;
        }

        /**
         * Setter for sponsor.
         * @param  sponsor  Object value for sponsor.
         * @return Builder
         */
        public Builder sponsor(Object sponsor) {
            this.sponsor = sponsor;
            return this;
        }

        /**
         * Setter for sponsorable.
         * @param  sponsorable  Object value for sponsorable.
         * @return Builder
         */
        public Builder sponsorable(Object sponsorable) {
            this.sponsorable = sponsorable;
            return this;
        }

        /**
         * Setter for tier.
         * @param  tier  Tier3 value for tier.
         * @return Builder
         */
        public Builder tier(Tier3 tier) {
            this.tier = tier;
            return this;
        }

        /**
         * Setter for maintainer.
         * @param  maintainer  Author7 value for maintainer.
         * @return Builder
         */
        public Builder maintainer(Author7 maintainer) {
            this.maintainer = maintainer;
            return this;
        }

        /**
         * Builds a new {@link Sponsorship} object using the set fields.
         * @return {@link Sponsorship}
         */
        public Sponsorship build() {
            return new Sponsorship(createdAt, nodeId, privacyLevel, sponsor, sponsorable, tier,
                    maintainer);
        }
    }
}
