/*
 * GitHubAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.github.api.models;

import java.util.ArrayList;
import java.util.List;
import java.util.TreeMap;

/**
 * Status15Enum to be used.
 */
public enum Status15Enum {
    REQUESTED,

    IN_PROGRESS,

    COMPLETED,

    QUEUED;


    private static TreeMap<String, Status15Enum> valueMap = new TreeMap<>();
    private String value;

    static {
        REQUESTED.value = "requested";
        IN_PROGRESS.value = "in_progress";
        COMPLETED.value = "completed";
        QUEUED.value = "queued";

        valueMap.put("requested", REQUESTED);
        valueMap.put("in_progress", IN_PROGRESS);
        valueMap.put("completed", COMPLETED);
        valueMap.put("queued", QUEUED);
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     */
    @com.fasterxml.jackson.annotation.JsonCreator
    public static Status15Enum fromString(String toConvert) {
        return valueMap.get(toConvert);
    }

    /**
     * Returns the string value associated with the enum member.
     * @return The string value against enum member.
     */
    @com.fasterxml.jackson.annotation.JsonValue
    public String value() {
        return value;
    }
        
    /**
     * Get string representation of this enum.
     */
    @Override
    public String toString() {
        return value.toString();
    }

    /**
     * Convert list of Status15Enum values to list of string values.
     * @param toConvert The list of Status15Enum values to convert.
     * @return List of representative string values.
     */
    public static List<String> toValue(List<Status15Enum> toConvert) {
        if (toConvert == null) {
            return null;
        }
        List<String> convertedValues = new ArrayList<>();
        for (Status15Enum enumValue : toConvert) {
            convertedValues.add(enumValue.value);
        }
        return convertedValues;
    }
} 