/*
 * GitHubAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.github.api.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.BaseModel;

/**
 * This is a model class for Verification type.
 */
public class Verification {
    private boolean verified;
    private String reason;
    private String payload;
    private String signature;

    /**
     * Default constructor.
     */
    public Verification() {
    }

    /**
     * Initialization constructor.
     * @param  verified  boolean value for verified.
     * @param  reason  String value for reason.
     * @param  payload  String value for payload.
     * @param  signature  String value for signature.
     */
    public Verification(
            boolean verified,
            String reason,
            String payload,
            String signature) {
        this.verified = verified;
        this.reason = reason;
        this.payload = payload;
        this.signature = signature;
    }

    /**
     * Getter for Verified.
     * @return Returns the boolean
     */
    @JsonGetter("verified")
    public boolean getVerified() {
        return verified;
    }

    /**
     * Setter for Verified.
     * @param verified Value for boolean
     */
    @JsonSetter("verified")
    public void setVerified(boolean verified) {
        this.verified = verified;
    }

    /**
     * Getter for Reason.
     * @return Returns the String
     */
    @JsonGetter("reason")
    public String getReason() {
        return reason;
    }

    /**
     * Setter for Reason.
     * @param reason Value for String
     */
    @JsonSetter("reason")
    public void setReason(String reason) {
        this.reason = reason;
    }

    /**
     * Getter for Payload.
     * @return Returns the String
     */
    @JsonGetter("payload")
    public String getPayload() {
        return payload;
    }

    /**
     * Setter for Payload.
     * @param payload Value for String
     */
    @JsonSetter("payload")
    public void setPayload(String payload) {
        this.payload = payload;
    }

    /**
     * Getter for Signature.
     * @return Returns the String
     */
    @JsonGetter("signature")
    public String getSignature() {
        return signature;
    }

    /**
     * Setter for Signature.
     * @param signature Value for String
     */
    @JsonSetter("signature")
    public void setSignature(String signature) {
        this.signature = signature;
    }

    /**
     * Converts this Verification into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "Verification [" + "verified=" + verified + ", reason=" + reason + ", payload="
                + payload + ", signature=" + signature + "]";
    }

    /**
     * Builds a new {@link Verification.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link Verification.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(verified, reason, payload, signature);
        return builder;
    }

    /**
     * Class to build instances of {@link Verification}.
     */
    public static class Builder {
        private boolean verified;
        private String reason;
        private String payload;
        private String signature;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  verified  boolean value for verified.
         * @param  reason  String value for reason.
         * @param  payload  String value for payload.
         * @param  signature  String value for signature.
         */
        public Builder(boolean verified, String reason, String payload, String signature) {
            this.verified = verified;
            this.reason = reason;
            this.payload = payload;
            this.signature = signature;
        }

        /**
         * Setter for verified.
         * @param  verified  boolean value for verified.
         * @return Builder
         */
        public Builder verified(boolean verified) {
            this.verified = verified;
            return this;
        }

        /**
         * Setter for reason.
         * @param  reason  String value for reason.
         * @return Builder
         */
        public Builder reason(String reason) {
            this.reason = reason;
            return this;
        }

        /**
         * Setter for payload.
         * @param  payload  String value for payload.
         * @return Builder
         */
        public Builder payload(String payload) {
            this.payload = payload;
            return this;
        }

        /**
         * Setter for signature.
         * @param  signature  String value for signature.
         * @return Builder
         */
        public Builder signature(String signature) {
            this.signature = signature;
            return this;
        }

        /**
         * Builds a new {@link Verification} object using the set fields.
         * @return {@link Verification}
         */
        public Verification build() {
            return new Verification(verified, reason, payload, signature);
        }
    }
}
