/*
 * GitHubAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.github.api.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.BaseModel;

/**
 * This is a model class for WorkflowJobwaitingevent type.
 */
public class WorkflowJobwaitingevent {
    private String action;
    private Enterprise1 enterprise;
    private Installation1 installation;
    private Organization2 organization;
    private Repository3 repository;
    private Sender sender;
    private WorkflowJob3 workflowJob;
    private Deployment6 deployment;

    /**
     * Default constructor.
     */
    public WorkflowJobwaitingevent() {
        action = "waiting";
    }

    /**
     * Initialization constructor.
     * @param  action  String value for action.
     * @param  repository  Repository3 value for repository.
     * @param  sender  Sender value for sender.
     * @param  workflowJob  WorkflowJob3 value for workflowJob.
     * @param  enterprise  Enterprise1 value for enterprise.
     * @param  installation  Installation1 value for installation.
     * @param  organization  Organization2 value for organization.
     * @param  deployment  Deployment6 value for deployment.
     */
    public WorkflowJobwaitingevent(
            String action,
            Repository3 repository,
            Sender sender,
            WorkflowJob3 workflowJob,
            Enterprise1 enterprise,
            Installation1 installation,
            Organization2 organization,
            Deployment6 deployment) {
        this.action = action;
        this.enterprise = enterprise;
        this.installation = installation;
        this.organization = organization;
        this.repository = repository;
        this.sender = sender;
        this.workflowJob = workflowJob;
        this.deployment = deployment;
    }

    /**
     * Getter for Action.
     * @return Returns the String
     */
    @JsonGetter("action")
    public String getAction() {
        return action;
    }

    /**
     * Setter for Action.
     * @param action Value for String
     */
    @JsonSetter("action")
    private void setAction(String action) {
        this.action = action;
    }

    /**
     * Getter for Enterprise.
     * @return Returns the Enterprise1
     */
    @JsonGetter("enterprise")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Enterprise1 getEnterprise() {
        return enterprise;
    }

    /**
     * Setter for Enterprise.
     * @param enterprise Value for Enterprise1
     */
    @JsonSetter("enterprise")
    public void setEnterprise(Enterprise1 enterprise) {
        this.enterprise = enterprise;
    }

    /**
     * Getter for Installation.
     * @return Returns the Installation1
     */
    @JsonGetter("installation")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Installation1 getInstallation() {
        return installation;
    }

    /**
     * Setter for Installation.
     * @param installation Value for Installation1
     */
    @JsonSetter("installation")
    public void setInstallation(Installation1 installation) {
        this.installation = installation;
    }

    /**
     * Getter for Organization.
     * @return Returns the Organization2
     */
    @JsonGetter("organization")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Organization2 getOrganization() {
        return organization;
    }

    /**
     * Setter for Organization.
     * @param organization Value for Organization2
     */
    @JsonSetter("organization")
    public void setOrganization(Organization2 organization) {
        this.organization = organization;
    }

    /**
     * Getter for Repository.
     * @return Returns the Repository3
     */
    @JsonGetter("repository")
    public Repository3 getRepository() {
        return repository;
    }

    /**
     * Setter for Repository.
     * @param repository Value for Repository3
     */
    @JsonSetter("repository")
    public void setRepository(Repository3 repository) {
        this.repository = repository;
    }

    /**
     * Getter for Sender.
     * @return Returns the Sender
     */
    @JsonGetter("sender")
    public Sender getSender() {
        return sender;
    }

    /**
     * Setter for Sender.
     * @param sender Value for Sender
     */
    @JsonSetter("sender")
    public void setSender(Sender sender) {
        this.sender = sender;
    }

    /**
     * Getter for WorkflowJob.
     * @return Returns the WorkflowJob3
     */
    @JsonGetter("workflow_job")
    public WorkflowJob3 getWorkflowJob() {
        return workflowJob;
    }

    /**
     * Setter for WorkflowJob.
     * @param workflowJob Value for WorkflowJob3
     */
    @JsonSetter("workflow_job")
    public void setWorkflowJob(WorkflowJob3 workflowJob) {
        this.workflowJob = workflowJob;
    }

    /**
     * Getter for Deployment.
     * @return Returns the Deployment6
     */
    @JsonGetter("deployment")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Deployment6 getDeployment() {
        return deployment;
    }

    /**
     * Setter for Deployment.
     * @param deployment Value for Deployment6
     */
    @JsonSetter("deployment")
    public void setDeployment(Deployment6 deployment) {
        this.deployment = deployment;
    }

    /**
     * Converts this WorkflowJobwaitingevent into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "WorkflowJobwaitingevent [" + "action=" + action + ", repository=" + repository
                + ", sender=" + sender + ", workflowJob=" + workflowJob + ", enterprise="
                + enterprise + ", installation=" + installation + ", organization=" + organization
                + ", deployment=" + deployment + "]";
    }

    /**
     * Builds a new {@link WorkflowJobwaitingevent.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link WorkflowJobwaitingevent.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(action, repository, sender, workflowJob)
                .enterprise(getEnterprise())
                .installation(getInstallation())
                .organization(getOrganization())
                .deployment(getDeployment());
        return builder;
    }

    /**
     * Class to build instances of {@link WorkflowJobwaitingevent}.
     */
    public static class Builder {
        private String action = "waiting";
        private Repository3 repository;
        private Sender sender;
        private WorkflowJob3 workflowJob;
        private Enterprise1 enterprise;
        private Installation1 installation;
        private Organization2 organization;
        private Deployment6 deployment;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  action  String value for action.
         * @param  repository  Repository3 value for repository.
         * @param  sender  Sender value for sender.
         * @param  workflowJob  WorkflowJob3 value for workflowJob.
         */
        public Builder(String action, Repository3 repository, Sender sender,
                WorkflowJob3 workflowJob) {
            this.action = action;
            this.repository = repository;
            this.sender = sender;
            this.workflowJob = workflowJob;
        }

        /**
         * Setter for action.
         * @param  action  String value for action.
         * @return Builder
         */
        public Builder action(String action) {
            this.action = action;
            return this;
        }

        /**
         * Setter for repository.
         * @param  repository  Repository3 value for repository.
         * @return Builder
         */
        public Builder repository(Repository3 repository) {
            this.repository = repository;
            return this;
        }

        /**
         * Setter for sender.
         * @param  sender  Sender value for sender.
         * @return Builder
         */
        public Builder sender(Sender sender) {
            this.sender = sender;
            return this;
        }

        /**
         * Setter for workflowJob.
         * @param  workflowJob  WorkflowJob3 value for workflowJob.
         * @return Builder
         */
        public Builder workflowJob(WorkflowJob3 workflowJob) {
            this.workflowJob = workflowJob;
            return this;
        }

        /**
         * Setter for enterprise.
         * @param  enterprise  Enterprise1 value for enterprise.
         * @return Builder
         */
        public Builder enterprise(Enterprise1 enterprise) {
            this.enterprise = enterprise;
            return this;
        }

        /**
         * Setter for installation.
         * @param  installation  Installation1 value for installation.
         * @return Builder
         */
        public Builder installation(Installation1 installation) {
            this.installation = installation;
            return this;
        }

        /**
         * Setter for organization.
         * @param  organization  Organization2 value for organization.
         * @return Builder
         */
        public Builder organization(Organization2 organization) {
            this.organization = organization;
            return this;
        }

        /**
         * Setter for deployment.
         * @param  deployment  Deployment6 value for deployment.
         * @return Builder
         */
        public Builder deployment(Deployment6 deployment) {
            this.deployment = deployment;
            return this;
        }

        /**
         * Builds a new {@link WorkflowJobwaitingevent} object using the set fields.
         * @return {@link WorkflowJobwaitingevent}
         */
        public WorkflowJobwaitingevent build() {
            return new WorkflowJobwaitingevent(action, repository, sender, workflowJob, enterprise,
                    installation, organization, deployment);
        }
    }
}
